spring:
  profiles:
    active: test
---
server:
  port: 1234
spring:
  application:
    name: ICICI Application- DEV Environment
datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/icicidb
  username: icici-dev
  password: icici-dev
config:
  activate:
    on-profile: dev
---
server:
  port: 2345
spring:
  application:
    name: ICICI Application- TEST Environment
datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/icicidb
  username: icici-test
  password: icici-test
config:
  activate:
    on-profile: test
---
server:
  port: 3456
spring:
  application:
    name: ICICI Application- PROD Environment
datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/icicidb
  username: icici-prod
  password: icici-prod
config:
  activate:
    on-profile: prod